# Generated by Django 4.2.2 on 2023-08-17 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Ad")),
                ("slug", models.SlugField(max_length=130, unique=True)),
            ],
            options={
                "verbose_name": "Brendlər",
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Ad")),
                ("slug", models.SlugField(max_length=130, unique=True)),
            ],
            options={
                "verbose_name": "Qrup",
                "verbose_name_plural": "Qruplar",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Ad")),
                ("slug", models.SlugField(max_length=130, unique=True)),
                (
                    "price_per_gram",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Qiymət 1 qram"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Kişi"), ("F", "Qadın"), ("U", "Unisex")],
                        default="U",
                        max_length=1,
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[("AW", "Payız/Qış"), ("SS", "Yaz/Yay")], max_length=2
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="store.brand",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(related_name="products", to="store.group"),
                ),
            ],
            options={
                "verbose_name": "Ətir",
                "verbose_name_plural": "Ətirlər",
            },
        ),
    ]
