# Generated by Django 4.2.2 on 2023-08-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={"verbose_name": "Brend", "verbose_name_plural": "Brendlər"},
        ),
        migrations.AlterField(
            model_name="product",
            name="gender",
            field=models.CharField(
                choices=[("M", "Kişi"), ("F", "Qadın"), ("U", "Unisex")],
                default="U",
                max_length=1,
                verbose_name="Cins",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="season",
            field=models.CharField(
                choices=[("AW", "Payız/Qış"), ("SS", "Yaz/Yay")],
                max_length=2,
                verbose_name="Fəsil",
            ),
        ),
    ]
