# Generated by Django 4.2.2 on 2023-08-29 20:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0003_favorite"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="telefon"
                    ),
                ),
                ("address", models.TextField(verbose_name="ünvan")),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="çatdırılıb"),
                ),
                (
                    "ordered_at",
                    models.DateTimeField(auto_now=True, verbose_name="sifariş tarixi"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sifariş",
                "verbose_name_plural": "Sifarişlər",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.PositiveSmallIntegerField(verbose_name="ölçü")),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(10)],
                        verbose_name="miqdar",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="store.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sifariş məhsulu",
                "verbose_name_plural": "Sifariş məhsulları",
            },
        ),
    ]
