# Generated by Django 4.2.2 on 2023-10-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_alter_order_phone_alter_orderitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="commentary",
            field=models.TextField(blank=True, null=True, verbose_name="rəy"),
        ),
    ]
