# Generated by Django 5.0.4 on 2024-04-24 15:31

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ad')),
                ('slug', models.SlugField(max_length=130, unique=True)),
            ],
            options={
                'verbose_name': 'Brend',
                'verbose_name_plural': 'Brendlər',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ad')),
                ('slug', models.SlugField(max_length=130, unique=True)),
            ],
            options={
                'verbose_name': 'Qrup',
                'verbose_name_plural': 'Qruplar',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.TextField(verbose_name='ünvan')),
                ('commentary', models.TextField(blank=True, null=True, verbose_name='rəy')),
                ('completed', models.BooleanField(default=False, verbose_name='çatdırılıb')),
                ('ordered_at', models.DateTimeField(auto_now_add=True, verbose_name='sifariş tarixi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sifariş',
                'verbose_name_plural': 'Sifarişlər',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ad')),
                ('slug', models.SlugField(max_length=130, unique=True)),
                ('price_per_gram', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Qiymət 1 qram')),
                ('gender', models.CharField(choices=[('M', 'Kişi'), ('F', 'Qadın'), ('U', 'Unisex')], default='U', max_length=1, verbose_name='Cins')),
                ('season', models.CharField(choices=[('AW', 'Payız/Qış'), ('SS', 'Yaz/Yay')], max_length=2, verbose_name='Fəsil')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.brand')),
                ('groups', models.ManyToManyField(related_name='products', to='store.group')),
            ],
            options={
                'verbose_name': 'Ətir',
                'verbose_name_plural': 'Ətirlər',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveSmallIntegerField(verbose_name='ölçü')),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='miqdar')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name': 'Sifariş məhsulu',
                'verbose_name_plural': 'Sifariş məhsulları',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name': 'Seçilmiş',
                'verbose_name_plural': 'Seçilmişlər',
                'unique_together': {('product', 'user')},
            },
        ),
    ]
